### ISSUE TITLE
Operations error if the lock has 0 in the mac address

### ISSUE THREAD

**Issue by dmtrTm** [kind3r/ttlock-sdk-js#10]
I have locks and 2 of them have problems, I noticed that their mac address contains 0, for example CC:82:FA:93:02:5B in the sdk work turns into {"address": "CC:82:FA:93:2:5B"..., and the mac address is E2:23:F0:0D:AD:00 in {"address": "E2:23:F0:D: AD:0". F0-true 0D-not correct. Can you tell me how to fix this error?

**Comment by kind3r** [comment]
That is a facepalm moment. I remember noticing this potential issues in the beginning and thinking "I'll fix this later"...

Can you try the latest  commit ?

**Comment by dmtrTm** [comment]
It's "later" now :)
Good news, I looked at your commit and it looks like a fix and a working solution.
Unfortunately, it will be possible to check on those locks only in a couple of days, I will definitely write to this thread.

Thank you for your prompt response!

**Comment by kind3r** [comment]
Hi @dmtrTm ,
Did you get a chancee to test ?

**Comment by dmtrTm** [comment]
@kind3r  Hello! 
I apologize for the long answer!

Yes, the solution worked. mac addresses including '00' '0D' work great!

At first, the synchronization was correct, but the error was in the control. After updating the library, the control worked and did not have to resynchronize
