### ISSUE TITLE
collect fingerprint from lock?

### ISSUE THREAD

**Issue by ftrentin** [kind3r/ttlock-sdk-js#12]
would it be possible to collect fingerprint from one lock and send to another? I still haven't figured out how to do this, I would like to collect all the cards and fingerprints from a lock and send it to a different one.

**Comment by kind3r** [comment]
Cards yes (they have unique s/n, this is all that is required from a card). Fingerprints not sure exactly by I would be inclined to say no. I remember seeing something related to backup but I'm not sure exactly how the fingerprints are backed up, if they are.

**Comment by ftrentin** [comment]
Thinking that way a backup and resotore would be enough. Then I could do a filter and find out how the data was stored. I will research about it, thanks for the answer.
