### ISSUE TITLE
error TS2367 on compile

### ISSUE THREAD

**Issue by ftrentin** [kind3r/ttlock-sdk-js#13]
when I run the command `npm i` it returns this error:

```
src/api/CommandEnvelope.ts:257:9 - error TS2367: This condition will always return 'true' since the types 'CommandType' and '-1' have no overlap.

257     if (this.commandType != -1 && typeof this.command == "undefined") {
            ~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.
npm ERR! code 2
npm ERR! path /tmp/ttlock-sdk-js
npm ERR! command failed
npm ERR! command sh -c npm run build
```

node v16.3.0
npm  v7.15.1

did this happen to anyone else?

**Comment by Fusseldieb** [comment]
Have you figured it out in the meantime or is this issue still present?

If it is, I'll take a look at it.

**Comment by DanielGPina** [comment]
> Have you figured it out in the meantime or is this issue still present?
> 
> If it is, I'll take a look at it.

It seems to be a recurring problem;

> src/api/CommandEnvelope.ts:257:9 - error TS2367: This condition will always return 'true' since the types 'CommandType' and '-1' have no overlap.
> 
> 257     if (this.commandType != -1 && typeof this.command == "undefined") {
>             ~~~~~~~~~~~~~~~~~~~~~~

node v16.6.2
npm v7.20.3

Had to change the build script from 
>"build": "rm -rf ./dist && tsc",
to
> "build": "rimraf ./dist && tsc"

since I am running on a this on a windows not really sure if related. 
I'll keep trying to take a look at this anyways. Thanks in Advance!

Edit: I know now it has nothing to do with windows, running it on a Debian atm.
same errors.

**Comment by kind3r** [comment]
Thanks @notEvil for the fix, it has been merged now. Sorry for the delay but I'm very busy IRL. I will resume development of this project late Sept when things will start to clear out.
@ftrentin and @DanielGPina could you please test and close issue.
Thanks.

**Comment by DanielGPina** [comment]
I would like to thanks @notEvil for the fix It seemed to be that easy but I wasn't sure. @kind3r I guess that fixes the CommandType error. But another error has occurred (let me know if you want me to start a new Issue or just keep it in this thread).
When it tries to connect I get this error:

> {"id":"f2cf34f5ec52","manufacturer":"unknown","model":"unknown","hardware":"unknown","firmware":"unknown","address":"F2:CF:34:F5:EC:52","rssi":-38,"protocolType":5,"protocolVersion":3,"scene":2,"groupId":0,"orgId":0,"lockType":5,"isTouch":true,"isUnlock":false,"hasEvents":false,"isSettingMode":false,"txPowerLevel":0,"batteryCapacity":100,"date":0,"isWristband":false,"isRoomLock":true,"isSafeLock":false,"isBicycleLock":false,"isLockcar":false,"isGlassLock":false,"isPadLock":false,"isCyLinder":false,"isRemoteControlDevice":false,"isDfuMode":false,"isNoLockService":false,"remoteUnlockSwitch":0,"disconnectStatus":0,"parkStatus":0,"lockSound":-1,"autoLockTime":-1,"privateData":{},"operationLog":[]}  
 >
>

> Peripheral connect start
> FATAL ERROR:  The value of "offset" is out of range. It must be >= 0 and <= 3. Received 5
>  1: 00007FF74BF0C27F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112159
>  2: 00007FF74BE9D2B6 v8::internal::WebSnapshotDeserializer::context_count+65430
>  3: 00007FF74BE9E16D node::OnFatalError+301
>  4: 00007FF74BE9D969 v8::internal::WebSnapshotDeserializer::context_count+67145
>  5: 00007FF74BECC0EC napi_fatal_error+156
>  6: 00007FF8BE6F17C7 Napi::Error::Fatal+23 [--ttlock-sdk-js\node_modules\usb\node_modules\node-addon-api\napi-inl.h]:L2252
>  7: 00007FF8BE73573E `handleCompletion'::`1'::catch$5+38 [--ttlock-sdk-js\node_modules\usb\src\transfer.cc]:L118
>  9: 00007FF8BE71ADD5 __FrameHandler4::CxxCallCatchBlock+277 [d:\agent\_work\4\s\src\vctools\crt\vcruntime\src\eh\frame.cpp]:L1393
> 10: 00007FF91BF91506 RtlCaptureContext2+1190
> 11: 00007FF8BE702704 handleCompletion+612 [--\ttlock-sdk-js\node_modules\usb\src\transfer.cc]:L114
> 12: 00007FF8BE6F23D8 Napi::ThreadSafeFunction::CallJS+104 [--\ttlock-sdk-js\node_modules\usb\node_modules\node-addon-api\napi-inl.h]:L4668
> 13: 00007FF74BECA2CE node_module_register+4798
> 14: 00007FF74BEC9B61 node_module_register+2897
> 15: 00007FF74BF6B15B uv_async_send+331
> 16: 00007FF74BF6A8EC uv_loop_init+1292
> 17: 00007FF74BF6AA8A uv_run+202
> 18: 00007FF74BF39D35 node::SpinEventLoop+309
> 19: 00007FF74BE55CC3 v8::internal::compiler::JSHeapBroker::root_index_map+53715
> 20: 00007FF74BED146D node::Start+221
> 21: 00007FF74BCF876C RC4_options+347756
> 22: 00007FF74CD548A8 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+14472
> 23: 00007FF91AEB7034 BaseThreadInitThunk+20
> 24: 00007FF91BF42651 RtlUserThreadStart+33
> 

Which feels weird because I can run it on the Hass Addon with the same hardware, perhaps its this method?
on TTLockBluetoothDevice.js
> parseManufacturerData(manufacturerData) {
>         // TODO: check offset is within the limits of the Buffer
>         //console.log(manufacturerData, manufacturerData.length);

**Comment by notEvil** [comment]
@kind3r no hurry, at least not for me :)

@DanielGPina I don't see the connection, the error message for TS2367 was pretty clear to me and I'd say is completely unrelated to parsing

**Comment by ftrentin** [comment]
I did a new test here, it worked as expected. thanks @kind3r and @DanielGPina !
