### ISSUE TITLE
Lock/unlock events notifications

### ISSUE THREAD

**Issue by kind3r** [kind3r/ttlock-sdk-js#5]
This issue is about implementing notifications from the lock when lock/unlock events happen in real time.

Unfortunately the Android SDK does not contain this part of the code so I'm looking for someone who can capture the BLE communication from the gateway to the lock to try to figure out what needs to be sent to the lock so it can start broadcasting those events. This can be done in 2 ways:
1. Adding a serial sniffer device between the gateway's ESP8266 and it's BLE module (the TX and RX pins are exposed via PCB header (see https://community.home-assistant.io/t/ttlock-support/61264/26). This would also require capturing the BLE traffic from the phone.
2. Using a BLE sniffer such as https://www.adafruit.com/product/2269 with wireshark and filtering the packets based on the MAC of the lock.

The logs should contain at least:
1. **Initial pairing** (this is done between phone and lock only so I need the log from the phone, @Fusseldieb can document this step). In order to be able to interpret the messages the full communication starting from pairing the lock is required as one of the first things the lock does is to generate an AES key that is used to encrypt all other messages.
2. **Adding the lock to a gateway** (this step sends the lock credentials to the gateway and probably activates the notifications from lock to gateway)
3. **Subscribing to notifications in the app**. Maybe not necessary but it's possible that only then will the gateway activate the notifications from the lock.
4. At least **one phisycal lock or unlock event** (that should receive a notification on the phone) via fingerprint, pin or card

I need help with this as I don't have a lock or a gateway.

**Comment by accelle17** [comment]
Which of the two ways has the high chance to get this events?
For #1, do you have a link on how to do the serial sniffing and how to connect the gateway to the sniffer?

**Comment by kind3r** [comment]
Both have the same chance I guess, cause we need to know how the gateway is able to enable the notifications on the lock and/or how it is able to keep the connection to the lock alive (right now with the SDK, the lock always disconnects after 3s of inactivity).

For method 1 you would need some sort of [logic analyzer](https://www.aliexpress.com/item/4001266883317.html?spm=a2g0s.9042311.0.0.79224c4dbfwjHP) that works with [Saleae](https://www.saleae.com/home2/) software to capture the communication between the ESP and BLE module of the gateway. Alternativelly you could use 2 [USB to serial](https://www.banggood.com/USB-to-Serial-Module-Downloader-CP2102-USB-to-TTL-STC-Download-Compatible-p-1536607.html?rmmds=myorder&cur_warehouse=CN) dongles to capture both TX and RX communication, but I don't know of any software capable of syncing those logs so you can view the correspondence between the 2 (what was sent and what was replied) but I think the BLE chip uses AT commands so it sould not be too difficult to match them with a simple script.
 
For the phone capture side @Fusseldieb has more details on how to create a BLE HCI log from an Android phone (or just google it).

I have ordered a gateway myself but it will take a few month to arrive.

**Comment by accelle17** [comment]
I have managed to setup the adafruit ble sniffer on a VM with Wireshark. Just to verify the procedure:

1. Reset and setup the lock with TTlock gateway again
2. Once paired, start running wireshark and use display filter: btle.advertising_address=='<lock bt address>'
3. Record
4. Unlock manually and wait for autolock to execute
5. Export/dump wireshark logs/data as well as the ble hci log from phone.

Any particular item on the logs that I need to check and provide to you?

**Comment by kind3r** [comment]
I need the full BLE capture logs starting with initial pairing up until the first notification. During the initial pairing is where the AES key is generated and used to encrypt all other packets, without it we can't make sense of the rest of the communication.
So what I would do is the following:
1. Remove the lock from TTLock app so that it resets to defaults
2. Start BLE capture
3. Pair the lock and gateway (not sure about the order) and setup notifications
4. Setup some credential (pin, card, finger whatever)
5. Unlock
6. Wait for the notificatification to arrive on the phone
7. Stop BLE capture
8. Filter capture by lock's MAC so only the communication related to the lock remains
9. Export the filtered capture

Then you can delete the lock from the app again so that new keys are generated etc.

**Comment by accelle17** [comment]
Here's the compressed capture. I've removed the lock from the gateway, re-add, add fingerprint and unlock manually. However, I couldn't get any unlock notifications from my phone. Not sure if it's the app problem since it's enabled (tried re-enabling it and check lock status on the later second capture.
I've sent the password on your gmail.
[ttlock_ble_sniff_20210130.zip](https://github.com/kind3r/ttlock-sdk-js/files/5897361/ttlock_ble_sniff_20210130.zip)

**Comment by kind3r** [comment]
Sorry for getting back so late.

Unfortunately the log does not contain anything new, except that the packets sent by the gateway have a few different parameters. But even so, the gateway is still disconnected in the end (I also tried this combination of settings in the sdk and got the same result).

But on the good side, I should be receiving my gateway next week so I will be able to perform my own tests and dig deeper into what is going on.

**Comment by kind3r** [comment]
I finally got my gateway yesterday and I had some time to play with it. Unfortunately I found nothing new from the communication between the lock and the gateway, but the weird thing was, the gateway always connected to the lock few seconds after it was locked or unlocked and read lock's event log.

After a few more hours of looking at the raw BLE data (and it's a lot of data with every device around me doing scans and advertisements and all the other broadcast related stuff) being puzzled about how the gateway knew to connect and read the event log it hit me: **the lock changes something in it's advertising data**.

And indeed, besides the battery byte that keeps fluctuating between 90 and 100%, there is another byte that changes. That byte contains the **current status of the lock**, 8 one bit settings, but only 4 of them where used in the official SDK:
```
0000 0000
|||| ||||__ (  1) isUnlock
|||| |||___ (  2) ????
|||| ||____ (  4) isSettingMode
|||| |_____ (  8) isTouch
||||_______ ( 16) parkStatus
|||________ ( 32) 
||_________ ( 64) 
|__________ (128) 
```
It looks like the 2nd bit is responsible for marking the existence of new events in the lock's log, and that is what the gateway uses to know when to connect and pull the events from the log.

So, what needs to happen in order to have this unlock notification functionality is to implement a passive scan that will monitor this new bit and react accordingly. Easier said than done, but still, at least I have a starting point.

**Comment by kind3r** [comment]
![image](https://user-images.githubusercontent.com/1621814/111917824-b1521a80-8a8a-11eb-84fd-68def5d08196.png)

Slow but steady making progress. The only issue is that **noble** does not implement passive scan so an active scan is required to get the advertisment packets. While this may not necessary be an issue for the lock (it does not seem to actually react to scan requests, but I still need to confirm this) it would affect other battery powered BLE devices as it forces them to respond to the scan requests.

**Comment by kind3r** [comment]
This is now implemented in the SDK via notifications about status changes and Operations Log

**Comment by w-gira** [comment]
This is a very interesting topic, I would like to implement a gateway with an esp32 to be able to read the events notifications
I can see that the gateway detects the bit change in the ad data and then sends:

7F 5A 00 00 00 00 00 00 00 25 55 10 33 49 FD 93 D5 85 79 44
93 DE DA D2 86 06 25 09 92 0D 0A

Then the lock notifies this

7F 5A 05 03 02 00 0A 00 49 54 55 10 A3 31 8C 1A 4F 41 6C 5C
D0 1C 26 26 32 8C 6D 1D 05 0D 0A

This is encrypted in AES ? What is the gateway sending to receive the events notifications?
Where can I get information about this?
