### ISSUE TITLE
  Method not implemented

### ISSUE THREAD

**Issue by Thejul67** [kind3r/ttlock-sdk-js#8]
Hi,

Thanks for this awsome project,

I tried to pair my lock with this project but i get the following error :

`scan started
{"id":"e606a3a898bd","name":"BTLock_bd98a8","manufacturer":"unknown","model":"unknown","hardware":"unknown","firmware":"unknown","address":"E6:6:A3:A8:98:BD","rssi":-81,"protocolType":5,"protocolVersion":3,"scene":2,"groupId":0,"orgId":0,"lockType":5,"isTouch":true,"isSettingMode":true,"isUnlock":false,"txPowerLevel":0,"batteryCapacity":100,"date":0,"isWristband":false,"isRoomLock":true,"isSafeLock":false,"isBicycleLock":false,"isLockcar":false,"isGlassLock":false,"isPadLock":false,"isCyLinder":false,"isRemoteControlDevice":false,"isDfuMode":false,"isNoLockService":false,"remoteUnlockSwitch":0,"disconnectStatus":0,"parkStatus":0,"autoLockTime":-1,"privateData":{}}

Trying to init the lock

========= init
========= init
========= AES key
========= AES key: 947c705c5103a1b1309eeaa00d542daa
========= admin
Setting adminPs 73079075 and unlockKey 76257105
========= admin: { adminPs: 73079075, unlockKey: 76257105 }
========= time
========= time
========= feature list
<Buffer 64 20 04 51 e1>
========= feature list Set(9) { 0, 5, 6, 7, 8, 12, 14, 18, 29 }
========= switchState
Error while initialising lock Error: Method not implemented.
    at TTLock.getSwitchStateCommand (/home/jul/ttlock/ttlock-sdk-js/dist/device/TTLockApi.js:189:15)
    at TTLock.initLock (/home/jul/ttlock/ttlock-sdk-js/dist/device/TTLock.js:144:42)
    at async TTLockClient.<anonymous> (/home/jul/ttlock/ttlock-sdk-js/examples/init.js:52:22)
[]
`
Is this error a bug maybe ?

Thanks

**Comment by kind3r** [comment]
Hi, your lock has feature `RESET_BUTTON = 29` which indeed is not implemented and I have no ideea what it does ... yet.

Just for posterity, could you also please post a link to your lock ?

I have disabled the unimplemented commands, so unless the lock pairing actually depends on them (doubtful) it should work now. Do a pull and try again.

**Comment by Thejul67** [comment]
Thanks for your answer,

Perfect its working !

My lock is a M530 model from aliexpress : 
https://fr.aliexpress.com/item/1005001785664927.html?spm=a2g0s.9042311.0.0.27426c37CfKIcu

You just done a great job !

But just a question :
Its very slow from the command (sudo npm run unlock) to the real opening of the lock.About 5 seconds
Can i do anything to decrease this delay ?

**Comment by kind3r** [comment]
Good to hear it works, weird model indeed.

It is slow because the `npm run` examples recompile the sources first. You can just run `node ./examples/unlock.js` or edit the package.json and remove `npm run build &&` in front of the commands.

But the purpose of this SDK is to be integrated in other applications. I also made a [HomeAssistant addon](https://github.com/kind3r/hass-addons) based on it. How are you planning to use your lock ?
